apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ecr-ptc-webhook.fullname" . }}-registries
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ecr-ptc-webhook.labels" . | nindent 4 }}
data:
  registries.yaml: |
    registries:
    {{- range .Values.registries }}
      - host: {{ .host | quote }}
        ecr_prefix: {{ .ecrPrefix | quote }}
        {{- if .dockerhub }}
        dockerhub: true
        {{- end }}
    {{- end }}
